# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailers',
            field=models.URLField(blank=True),
        ),
    ]
