# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgallery', '0002_auto_20171126_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailers',
        ),
    ]
